# Generated by Django 5.2.7 on 2025-11-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='unavailable_dates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
