# Generated by Django 5.2.7 on 2025-11-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_worker_unavailable_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('schedule', models.JSONField(default=dict)),
                ('employee_stats', models.JSONField(default=dict)),
            ],
        ),
    ]
