# Generated by Django 5.2.7 on 2025-11-12 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['month']},
        ),
    ]
