# Generated by Django 5.2.7 on 2025-11-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_schedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='schedule_stats',
            field=models.JSONField(default=dict),
        ),
    ]
