# Generated by Django 5.2.7 on 2025-11-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_schedule_schedule_stats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='month',
            new_name='date',
        ),
    ]
