# Generated by Django 5.2.7 on 2025-11-14 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_alter_schedule_options_rename_month_schedule_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['schedule_period']},
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='employee_stats',
            new_name='per_day_schedule',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='schedule',
            new_name='per_employee_schedule',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='date',
            new_name='schedule_period',
        ),
    ]
