# Generated by Django 5.2.7 on 2025-11-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='per_day_schedule',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='per_employee_schedule',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_stats',
            field=models.JSONField(default=list),
        ),
    ]
