# Generated by Django 5.2.7 on 2025-12-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_alter_schedule_per_day_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='assign_least_shifts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='assign_least_weekends',
            field=models.BooleanField(default=False),
        ),
    ]
