# Generated by Django 5.2.7 on 2025-12-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_worker_assign_least_shifts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-schedule_period']},
        ),
    ]
